### PR TITLE
fix dependencies and python requirement in pyproject.toml

### PR DESCRIPTION
**Pull request by lorepirri**
Hi @idanmoradarthas , I noticed that your `pyproject.toml` has some leftover in `tool.peotry.dependencies` (there might be a misspelled `peotry` vs `poetry`). Would you consider using the beta feature of `setuptools` instead, to specify your dependencies? https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata

### CODE REVIEW

**Comment by idanmoradarthas** [comment]
This what happens when I let chatgpt wtite my pyproject.toml file. I'm a bit busy this days. I will review your PR as soon as I can. Thank you very much for alerting me and create this PR.

**Comment by lorepirri** [comment]
Sure! Thank you for maintaining this project and keeping it alive!

**Comment by idanmoradarthas** [comment]
Great PR! Thanks for noticing, sorry for the delayed response

**Comment by lorepirri** [comment]
Sure! Thank you!

**Pull request merged**
