### PR TITLE
Axes.get_xticks() returns an array, not a numpy array fix

### PR DESCRIPTION
**Pull request by idanmoradarthas**
* Fixed get_ticks() to list if matplotlib version is less than 3.8.4
* Fixed some tests
* Update supporting packages version
* Update version

### CODE REVIEW

**Comment by lorepirri** [comment]
Hi @idanmoradarthas , thanks for this PR. I think there are two more `get_xticks()` to fix.

https://github.com/idanmoradarthas/DataScienceUtils/blob/74c323e828938603b505a2f85921277fb47032df/ds_utils/preprocess.py#L244

https://github.com/idanmoradarthas/DataScienceUtils/blob/74c323e828938603b505a2f85921277fb47032df/ds_utils/preprocess.py#L259

The code seems good. Thanks for fixing the tests. You could also think about supporting only `matplotlib >=3.8.4` so that you don't have the check for the `np.array` instance.

If you are planning to bump the version and do a new pypi release, could you please create a version tag `1.7.4` for it? We missed the tag for `1.7.3`.

**Comment by idanmoradarthas** [comment]
Hey @lorepirri, I saw your comment. I'll try and answer it as soon as possible, I'm a bit busy nowadays

**Comment by lorepirri** [comment]
Sure @idanmoradarthas no problem, thanks!

**Review by lorepirri — APPROVED** [review]
Hey @idanmoradarthas this looks good to me! Thanks for working further on this and fixing all the leftovers.

Would it be beneficial for you adding a couple of workflows on GitHub actions, one for a PyPi + GH release, and another one for running tests at every commit? I see some `.travis` configuration but could not find any recent run there. Let me know if you need further help.

**Comment by idanmoradarthas** [comment]
Well I'm not that familiar with GitHub actions, as I'm not a dev ops guy, more of a data scientists. You can see that I have script for auto deploy, but they still need to be run manually. 

I had used TravisCI and Coveralls 4 years ago for PR approval, but Then Travis changed their pricing plans and demanded credit card for the free tier, which I'm never going to give my credit card number for something that is suppose to be free. Now I've looked at circleci recently as an alternative for Travis, but I was too busy. Mabye in the future I'll do a deep dive into it.

**Pull request merged**
